import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { FileText, Bot, Upload, Globe, ArrowRight, Clock, } from 'lucide-react';
import Card from '@/components/ui/Card';
import { useAppStore } from '@/lib/store';
export default function Home(_a) {
    var _b = _a.recentLiterature, recentLiterature = _b === void 0 ? [] : _b;
    var tasks = useAppStore(function (s) { return s.tasks; });
    var currentTaskId = useAppStore(function (s) { return s.currentTaskId; });
    var recentTasks = Object.values(tasks).slice(0, 3);
    var activeTask = currentTaskId ? tasks[currentTaskId] : null;
    var quickStart = [
        { to: '/library', icon: Upload, label: '导入 PDF', desc: '从本地文件导入' },
        { to: '/library', icon: Globe, label: '从 Semantic Scholar', desc: '在线搜索导入' },
        { to: '/agent', icon: Bot, label: '新建综述任务', desc: 'AI 协作写作' },
    ];
    var getTimeEstimate = function (progress) {
        var remaining = (1 - progress) * 30;
        if (remaining < 1)
            return '即将完成';
        return "\u9884\u8BA1 ".concat(Math.round(remaining), " \u5206\u949F");
    };
    return (_jsx("div", { className: "h-full overflow-auto p-6", children: _jsxs("div", { className: "max-w-4xl mx-auto", children: [_jsxs("div", { className: "mb-8", children: [_jsx("h1", { className: "text-2xl font-semibold text-text-primary mb-1", children: "\u6B22\u8FCE\u56DE\u6765" }), _jsx("p", { className: "text-sm text-text-secondary", children: activeTask ? '你有一个进行中的任务' : '开始你的学术研究之旅' })] }), activeTask && (_jsxs("div", { className: "mb-8", children: [_jsx("h2", { className: "text-[11px] font-medium text-text-muted uppercase tracking-wider mb-3", children: "\u7EE7\u7EED\u5199\u4F5C" }), _jsx(Card, { clickable: true, className: "group", children: _jsxs(Link, { to: "/editor/1", className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("h3", { className: "text-base font-medium text-text-primary truncate mb-1", children: activeTask.topic }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { className: "flex gap-1.5", children: [activeTask.currentAgent && (_jsx("span", { className: "text-xs px-2 py-0.5 bg-primary/10 text-primary rounded", children: activeTask.currentAgent })), _jsx("span", { className: "text-xs text-text-muted", children: activeTask.status })] }), _jsx("span", { className: "text-xs text-text-muted", children: getTimeEstimate(activeTask.progress) })] }), _jsx("div", { className: "w-full h-1.5 bg-surface-hover rounded-full overflow-hidden mt-3", children: _jsx("div", { className: "h-full bg-primary rounded-full transition-all duration-500", style: { width: "".concat(activeTask.progress * 100, "%") } }) })] }), _jsx(ArrowRight, { size: 18, className: "text-text-muted ml-4 group-hover:text-primary transition-colors" })] }) })] })), _jsx("div", { className: "grid grid-cols-3 gap-3 mb-8", children: quickStart.map(function (item) {
                        var Icon = item.icon;
                        return (_jsx(Link, { to: item.to, children: _jsx(Card, { clickable: true, className: "h-full group", children: _jsxs("div", { className: "flex items-start gap-3", children: [_jsx("div", { className: "w-9 h-9 rounded-md bg-primary/10 flex items-center justify-center shrink-0", children: _jsx(Icon, { size: 16, className: "text-primary" }) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("span", { className: "text-[14px] font-medium text-text-primary block", children: item.label }), _jsx("span", { className: "text-[12px] text-text-muted", children: item.desc })] })] }) }) }, item.label));
                    }) }), recentLiterature.length > 0 && (_jsxs("div", { className: "mb-8", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsx("h2", { className: "text-[11px] font-medium text-text-muted uppercase tracking-wider", children: "\u6700\u8FD1\u6587\u732E" }), _jsx(Link, { to: "/library", className: "text-xs text-primary hover:underline", children: "\u67E5\u770B\u5168\u90E8" })] }), _jsx("div", { className: "space-y-2", children: recentLiterature.slice(0, 5).map(function (lit) {
                                var _a;
                                return (_jsx(Card, { clickable: true, className: "group", children: _jsxs(Link, { to: "/reader/".concat(lit.id), className: "flex items-center gap-3", children: [_jsx("div", { className: "w-8 h-8 rounded bg-surface flex items-center justify-center shrink-0", children: _jsx(FileText, { size: 14, className: "text-text-muted" }) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("h4", { className: "text-[13px] font-medium text-text-primary truncate", children: lit.title }), _jsxs("p", { className: "text-[11px] text-text-muted", children: [((_a = lit.authors[0]) === null || _a === void 0 ? void 0 : _a.name) || 'Unknown', " \u00B7 ", lit.year || 'n.d.', lit.citation_count ? " \u00B7 \u88AB\u5F15 ".concat(lit.citation_count, " \u6B21") : ''] })] }), _jsx(ArrowRight, { size: 14, className: "text-text-muted opacity-0 group-hover:opacity-100 transition-opacity" })] }) }, lit.id));
                            }) })] })), recentTasks.length > 0 && !activeTask && (_jsxs("div", { children: [_jsx("h2", { className: "text-[11px] font-medium text-text-muted uppercase tracking-wider mb-3", children: "\u6700\u8FD1\u4EFB\u52A1" }), _jsx("div", { className: "space-y-2", children: recentTasks.map(function (task) { return (_jsxs("div", { className: "flex items-center gap-3 p-3 bg-surface border border-border rounded-md", children: [_jsx(Clock, { size: 14, className: "text-text-muted shrink-0" }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: "text-[13px] text-text-primary truncate", children: task.topic }), _jsx("p", { className: "text-[11px] text-text-muted", children: task.status })] }), _jsx("div", { className: "w-16 h-1.5 bg-surface-hover rounded-full overflow-hidden shrink-0", children: _jsx("div", { className: "h-full bg-primary rounded-full transition-all duration-300", style: { width: "".concat(task.progress * 100, "%") } }) })] }, task.id)); }) })] }))] }) }));
}
