import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { Search, Plus, FileText } from 'lucide-react';
import Button from '@/components/ui/Button';
import Input from '@/components/ui/Input';
export default function NoteSelector(_a) {
    var notes = _a.notes, onSelect = _a.onSelect, onCancel = _a.onCancel;
    var _b = useState(''), search = _b[0], setSearch = _b[1];
    var _c = useState(''), newNoteTitle = _c[0], setNewNoteTitle = _c[1];
    var _d = useState('select'), mode = _d[0], setMode = _d[1];
    var filtered = notes.filter(function (n) {
        return n.title.toLowerCase().includes(search.toLowerCase());
    });
    return (_jsx("div", { className: "fixed inset-0 z-[100] flex items-center justify-center bg-black/30", children: _jsxs("div", { className: "bg-card border border-border rounded-xl shadow-xl w-[420px] max-h-[80vh] flex flex-col", children: [_jsxs("div", { className: "px-4 py-3 border-b border-border", children: [_jsx("h3", { className: "text-sm font-semibold text-text-primary", children: "\u6DFB\u52A0\u5230\u7B14\u8BB0" }), _jsx("p", { className: "text-xs text-text-muted mt-0.5", children: "\u9009\u62E9\u4E00\u4E2A\u73B0\u6709\u7B14\u8BB0\u6216\u521B\u5EFA\u65B0\u7B14\u8BB0" })] }), _jsxs("div", { className: "flex border-b border-border", children: [_jsx("button", { onClick: function () { return setMode('select'); }, className: "flex-1 py-2 text-xs font-medium transition-colors ".concat(mode === 'select'
                                ? 'text-primary border-b-2 border-primary'
                                : 'text-text-muted hover:text-text-secondary'), children: "\u9009\u62E9\u7B14\u8BB0" }), _jsx("button", { onClick: function () { return setMode('create'); }, className: "flex-1 py-2 text-xs font-medium transition-colors ".concat(mode === 'create'
                                ? 'text-primary border-b-2 border-primary'
                                : 'text-text-muted hover:text-text-secondary'), children: "\u65B0\u5EFA\u7B14\u8BB0" })] }), mode === 'select' ? (_jsxs(_Fragment, { children: [_jsx("div", { className: "p-3", children: _jsxs("div", { className: "relative", children: [_jsx(Search, { size: 12, className: "absolute left-2 top-1/2 -translate-y-1/2 text-text-muted" }), _jsx(Input, { value: search, onChange: function (e) { return setSearch(e.target.value); }, placeholder: "\u641C\u7D22\u7B14\u8BB0...", className: "pl-7 text-xs" })] }) }), _jsx("div", { className: "flex-1 overflow-auto px-3 pb-3 min-h-[200px]", children: filtered.length === 0 ? (_jsx("div", { className: "text-center text-text-muted py-8 text-xs", children: notes.length === 0 ? '暂无笔记' : '未找到匹配的笔记' })) : (_jsx("div", { className: "space-y-1", children: filtered.map(function (note) { return (_jsx("button", { onClick: function () { return onSelect(note.id); }, className: "w-full text-left px-3 py-2 rounded-lg hover:bg-surface-hover transition-colors group", children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(FileText, { size: 13, className: "text-text-muted shrink-0" }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("div", { className: "text-xs font-medium text-text-primary truncate", children: note.title }), _jsx("div", { className: "text-[10px] text-text-muted line-clamp-1", children: note.content.slice(0, 60) || '无内容' })] })] }) }, note.id)); }) })) })] })) : (_jsxs("div", { className: "p-3 flex-1 min-h-[200px]", children: [_jsx(Input, { value: newNoteTitle, onChange: function (e) { return setNewNoteTitle(e.target.value); }, placeholder: "\u8F93\u5165\u65B0\u7B14\u8BB0\u6807\u9898...", className: "text-xs" }), _jsx("div", { className: "mt-3 flex justify-end", children: _jsxs(Button, { size: "sm", onClick: function () { return onSelect(null, newNoteTitle.trim()); }, disabled: !newNoteTitle.trim(), children: [_jsx(Plus, { size: 12 }), "\u521B\u5EFA\u5E76\u6DFB\u52A0"] }) })] })), _jsx("div", { className: "px-4 py-3 border-t border-border flex justify-end gap-2", children: _jsx(Button, { size: "sm", variant: "ghost", onClick: onCancel, children: "\u53D6\u6D88" }) })] }) }));
}
